trigger: none

schedules:
- cron: "45 3-5 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --iam --username $HUA7_USERNAME --password $PASSWORD --git $HUA7_GIT
    displayName: 'Run'
    env:
      PARENT_USER: huyansheng000