trigger: none

schedules:
- cron: "25 6-8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --iam --username $HUA10_USERNAME --password $PASSWORD --git $HUA10_GIT
    displayName: 'Run'
    env:
      PARENT_USER: huyansheng