trigger: none

schedules:
- cron: "5 0-2 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build
  timeoutInMinutes: 30
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --username $WANG_TWO_USERNAME --password $WANG_PASSWORD --git $WANG_TWO_GIT
    displayName: 'Run'
